# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "43ee0f386769c66d5ec8dec7a8e60335"
name = "testing-react-19"
handle = "testing-react-19"
application_url = "https://walt-breakdown-excess-kentucky.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "squark-dev3.myshopify.com"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = ""

[auth]
redirect_urls = [
  "https://walt-breakdown-excess-kentucky.trycloudflare.com/auth/callback",
  "https://walt-breakdown-excess-kentucky.trycloudflare.com/auth/shopify/callback",
  "https://walt-breakdown-excess-kentucky.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-07"

[pos]
embedded = false
